const types = {
  anticipation: 'models.operations.anticipation',
  anticipation_fee: 'models.operations.anticipation_fee',
  anticipationMessage: 'models.operations.anticipation_message',
  boleto: 'models.operations.boleto',
  boletoRefundFee: 'models.operations.boleto_refund_fee',
  chargeback: 'models.operations.chargeback',
  chargeback_refund: 'models.operations.chargeback_refund',
  credit_card: 'models.operations.credit_card',
  credito_em_conta: 'models.operations.transfer',
  debit: 'models.operations.debit',
  failed: 'models.operations.failed',
  from: 'models.operations.from',
  gateway: 'models.operations.gateway_service',
  installment: 'models.operations.installment',
  inter_recipient: 'models.operations.inter_recipient',
  mdr: 'models.operations.mdr',
  refund: 'models.operations.refund',
  refund_reversal: 'models.operations.refund_reversal',
  refund_reversal_description: 'models.operations.refund_reversal_description',
  ted: 'models.operations.transfer',
  tedFee: 'models.operations.transfer_fee',
  to: 'models.operations.to',
  transfer: 'models.operations.transfer',
  transferId: 'models.operations.transfer_id',
  withdraw: 'models.operations.withdraw',
}

export default types
