export default `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a turpis auctor, luctus lorem eu, pharetra libero. Nunc rutrum metus et porttitor cursus. Vestibulum eget est eget nibh laoreet faucibus. Praesent non bibendum orci. Nunc aliquam molestie est, sit amet mattis sem suscipit vel. Fusce vitae diam dolor. Nulla ultricies, orci id tempor vestibulum, eros est tristique lorem, non varius risus velit ac ex. Proin malesuada sed ante vel efficitur. Nunc finibus in sapien id sagittis. Morbi tellus augue, molestie eget metus sed, tempus lobortis arcu. Integer in vulputate velit. Phasellus aliquam neque non tortor mollis lobortis. Mauris mollis lacinia neque, vitae tempor tellus efficitur luctus.

Etiam ac justo eget lorem pharetra faucibus. Donec porttitor, arcu ac cursus accumsan, nulla odio maximus odio, in feugiat magna sapien bibendum quam. Suspendisse vitae eros purus. Praesent vestibulum, leo non auctor egestas, mauris sem congue ex, porta blandit sem dolor at odio. Vestibulum vitae enim laoreet, iaculis metus nec, iaculis tellus. Donec nec consequat libero. Sed fermentum odio eros, ac iaculis nunc commodo vel. Phasellus feugiat a lacus at lacinia. In a dui libero. Phasellus sit amet convallis sem. Nulla in quam vitae lacus hendrerit tincidunt ut sed nulla. Sed sed sagittis mauris, at blandit sem. Mauris hendrerit cursus convallis. Phasellus lacinia quam neque, a tristique libero lobortis a. Fusce ac porttitor enim. Fusce condimentum porttitor mi, sit amet molestie dolor ultricies vitae.

Phasellus neque diam, laoreet in commodo non, porttitor sit amet leo. Curabitur vitae ipsum mauris. Fusce ullamcorper ipsum ut bibendum blandit. Fusce sagittis lacus id elementum dapibus. Integer feugiat efficitur lorem, nec ultricies nunc malesuada id. Praesent eget dui eu odio dapibus aliquet. Nulla venenatis diam porttitor, cursus nunc at, convallis metus. Donec suscipit mattis tincidunt. Donec vel elit a magna aliquet tristique vitae eget dolor. Nam ac metus porta, ultrices massa eget, cursus dui. Nulla vitae condimentum ante, sit amet ullamcorper dui. Nam nec dictum massa. Maecenas dignissim ante quis arcu aliquet sodales. Nullam volutpat vel augue nec faucibus. Nulla vel mauris consequat elit consectetur varius.

Aliquam blandit consequat justo, sit amet molestie risus. Aenean imperdiet fringilla gravida. Sed in nisl dolor. In auctor nulla vitae magna sollicitudin congue. Etiam sapien mi, cursus nec tempus quis, interdum ut neque. In at eros quis dui mollis gravida at eu sem. Mauris id vehicula augue, vitae malesuada mauris. Praesent tincidunt sollicitudin scelerisque. Quisque accumsan dictum tortor, sit amet vestibulum nisi iaculis nec. Nam in consectetur est. Vivamus eu viverra elit, eget dictum leo. Curabitur in lorem odio.

Maecenas sed nisl nulla. Integer nec dui sagittis, commodo ligula sit amet, feugiat neque. Cras dapibus metus eu ante vehicula, et suscipit enim ultricies. Nullam aliquam, nunc et interdum iaculis, tortor nulla egestas massa, at pellentesque massa tortor nec est. Pellentesque a urna non velit viverra molestie elementum non justo. Nunc et congue quam. Quisque tempus rutrum vestibulum. Vestibulum mollis nibh tempor pellentesque tempor. Quisque sodales feugiat nulla, at facilisis magna euismod a. Ut ac justo nisi.
`
